# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table_Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from DB import workDB

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(954, 688)
        font = QtGui.QFont()
        font.setPointSize(9)
        Dialog.setFont(font)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(510, 130, 401, 361))
        self.listWidget.setObjectName("listWidget")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(510, 510, 401, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 550, 401, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(510, 90, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget_2 = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 130, 431, 361))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 510, 431, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 550, 431, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(30, 80, 201, 31))
        self.checkBox.setObjectName("checkBox")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 131, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(720, 20, 211, 28))
        self.pushButton_7.setObjectName("pushButton_7")

        # Поключение кнопок
        self.pushButton.clicked.connect(self.add_new_program)
        self.pushButton_2.clicked.connect(self.delete_program)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Добавить программу"))
        self.pushButton_2.setText(_translate("Dialog", "Удалить программу"))

        self.label.setText(_translate("Dialog", "Программы:"))
        self.label_2.setText(_translate("Dialog", "Админы:"))
        self.pushButton_4.setText(_translate("Dialog", "Добавить"))
        self.pushButton_5.setText(_translate("Dialog", "Удалить"))
        self.checkBox.setText(_translate("Dialog", "Уровня"))
        self.comboBox.setItemText(0, _translate("Dialog", "1- го"))
        self.comboBox.setItemText(1, _translate("Dialog", "2 - го"))
        self.pushButton_7.setText(_translate("Dialog", "Обновить"))

        #Заполнение таблицы программ
        list_programs = workDB.get_programs()
        self.listWidget.addItems(list_programs.values())

    def add_new_program(self):
        program_name, ok = QtWidgets.QInputDialog.getText(None, 'Добавить программу', 'Введите название программы:')
        if ok and program_name:
            self.listWidget.addItem(program_name)
            workDB.add_program(program_name)


    def delete_program(self):
        selected_items = self.listWidget.selectedItems()
        for item in selected_items:
            program_name = item.text()
            removed_item = self.listWidget.takeItem(self.listWidget.row(item))
            workDB.delete_program(program_name)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
